import { SearchOutlined } from '@ant-design/icons'
import { Row, Select, Space, Typography,Tag, Col, List } from 'antd'
import Head from 'next/head'
import Image from 'next/image'
import Carousel from '../components/Carousel'
import App from '../components/Item'

export default function Home() {
  const array =[
    {
      name: 'Syokimau Mansion',
      location: ' 1.5KM from Mombasa Road.',
      price:"Ksh 35M",
      image:'/PHOTOS/syk/1.jpg'
    },
    {
      name: '50 by 100 Plots',
      location:" 3KM off Namanga ",
      price:"Kshs 800, 000",
      image:'/PHOTOS/ksj/1.jpg'
    },
    {
      name: '50 by 100',
      location: '2KM from Makindu town ',
      price:" Kshs 185,000 Cash payment",
      image:'/PHOTOS/mknd/1.jpg'
    },

  ]
  const data = [
    {
      title:"	Land Investment",
      desc:"Looking for a solid investment opportunity? Look no further than land investment with Guton Kenya Ltd. Our experienced team will work with you to identify the best land investment opportunities and provide comprehensive support throughout the entire investment process. "
    },
    {
      title: 'Property Management ',
      desc:"We work closely with property owners to ensure that their investments are well taken care of and that their tenants are happy and satisfied. With our property management services, you can sit back and relax while we handle the day-to-day operations of your property."
    },
    {
      title: 'Estate Agency i.e., Commercial, Industrial and Residential Letting and Sales',
      desc:"Looking for a solid investment opportunity? Look no further than land investment with Guton Kenya Ltd. Our experienced team will work with you to identify the best land investment opportunities and provide comprehensive support throughout the entire investment process. "
    },
    {
      title: 'Property Consultancy',
      desc:"At Guton Kenya Ltd, we offer a comprehensive estate agency service that covers commercial, industrial, and residential letting and sales.Whether you're looking to lease or buy a property, our team of experienced agents will work closely with you to understand your needs and find the right property that meets your requirements.  "
    },
  ];
  return (
    <div style={{width:'100%'}}>
      <Head>
        <title>Guton Kenya LTD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{width:'100%'}}>
      <Carousel />
      <div style={{background:'#141a86',paddingTop:20,borderBottom:'2px solid #141a86'}}>
      <Row justify="center" style={{padding:20}}>
        <Tag icon={<SearchOutlined />} color="#141a86">What Are You Searching For ?</Tag>
      </Row>
      <div className='container' style={{width:'100%',minHeight:100,padding:20,display:'flex',alignItems:'center',flexDirection:"row",gap:20,justifyContent:'space-evenly'}}>
       <Select
       size='large'
        showSearch
        style={{width:'100%'}}
        placeholder="Select Location"
        optionFilterProp="children"
        filterOption={(input, option) => (option?.label ?? '').includes(input)}
        filterSort={(optionA, optionB) =>
          (optionA?.label ?? '').toLowerCase().localeCompare((optionB?.label ?? '').toLowerCase())
        }
        options={[
          {
            value: '1',
            label: 'Not Identified',
          },
          {
            value: '2',
            label: 'Closed',
          },
          {
            value: '3',
            label: 'Communicated',
          },
          {
            value: '4',
            label: 'Identified',
          },
          {
            value: '5',
            label: 'Resolved',
          },
          {
            value: '6',
            label: 'Cancelled',
          },
        ]}
      />
       <Select
       size='large'
        style={{width:'100%'}}
        showSearch
        placeholder="Select Price"
        optionFilterProp="children"
        filterOption={(input, option) => (option?.label ?? '').includes(input)}
        filterSort={(optionA, optionB) =>
          (optionA?.label ?? '').toLowerCase().localeCompare((optionB?.label ?? '').toLowerCase())
        }
        options={[
          {
            value: '1',
            label: 'Not Identified',
          },
          {
            value: '2',
            label: 'Closed',
          },
          {
            value: '3',
            label: 'Communicated',
          },
          {
            value: '4',
            label: 'Identified',
          },
          {
            value: '5',
            label: 'Resolved',
          },
          {
            value: '6',
            label: 'Cancelled',
          },
        ]}
      />
       <Select
       size='large'
        showSearch
        style={{width:'100%'}}
        placeholder="Select Area"
        optionFilterProp="children"
        filterOption={(input, option) => (option?.label ?? '').includes(input)}
        filterSort={(optionA, optionB) =>
          (optionA?.label ?? '').toLowerCase().localeCompare((optionB?.label ?? '').toLowerCase())
        }
        options={[
          {
            value: '1',
            label: 'Not Identified',
          },
          {
            value: '2',
            label: 'Closed',
          },
          {
            value: '3',
            label: 'Communicated',
          },
          {
            value: '4',
            label: 'Identified',
          },
          {
            value: '5',
            label: 'Resolved',
          },
          {
            value: '6',
            label: 'Cancelled',
          },
        ]}
      />
      </div>
      </div>
      <div className='container'>
      <Row justify="start">
        <Typography.Title>
         Featured Projects
        </Typography.Title>
      </Row>
      <Row gutter={16}>
      {
          array.map(i => (
           <Col xs={24} sm={24} md={8} lg={8} xl={8}>
            <App data={i} />
           </Col>
          ))
        }
       </Row>
      </div>
      <div className='container'>
      <Row justify="start">
        <Typography.Title>
       Our Service
        </Typography.Title>
      </Row>
      <List
    itemLayout="horizontal"
    dataSource={data}
    renderItem={(item, index) => (
      <List.Item>
        <List.Item.Meta
          title={item.title}
          description={item.desc}
        />
      </List.Item>
    )}
  />
      </div>
      </main>
    </div>
  )
}
